name: Add release ZIP

on:
  release:
    types: [published]

jobs:
  create-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Install composer dependencies
        run: |
          composer install --no-dev
          composer dump-autoload --optimize

      - name: Create ZIP
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          PLUGIN_SLUG="${PWD##*/}"
          VERSION="${TAG_NAME//v}"
          # put the plugin in a folder
          shopt -s extglob dotglob
          mkdir $PLUGIN_SLUG
          mv !($PLUGIN_SLUG) $PLUGIN_SLUG
          shopt -u dotglob
          # reformat .distignore: remove all empty lines, leading slashes and prefix with the folder
          sed "/^[[:space:]]*$/d;s#^/##;s#^#$PLUGIN_SLUG/#" $PLUGIN_SLUG/.distignore > .zipignore
          sed "/^[[:space:]]*$/d;s#^/##;s#^#$PLUGIN_SLUG/#" $PLUGIN_SLUG/.distignore-light > .zipignore-light
          # create zip files
          ZIP_FILE_NAME_CJK=$PLUGIN_SLUG.$VERSION.CJK.zip
          ZIP_FILE_NAME=$PLUGIN_SLUG.$VERSION.zip
          zip -rq $ZIP_FILE_NAME_CJK $PLUGIN_SLUG -x@.zipignore
          zip -rq $ZIP_FILE_NAME $PLUGIN_SLUG -x@.zipignore-light
          # store file names for next step
          echo "zip_file_name_cjk=$ZIP_FILE_NAME_CJK" >> $GITHUB_ENV
          echo "zip_file_name=$ZIP_FILE_NAME" >> $GITHUB_ENV

      - name: Add ZIP to release asseets
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: >
            ${{ env.zip_file_name }}
            ${{ env.zip_file_name_cjk }}
          gzip: false
          allow_override: true